#!/usr/bin/env bun
import{mkdtempSync,rmSync,writeFileSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{spawnSync}from"node:child_process";
const root=new URL("..",import.meta.url).pathname,bin=`${root}/BasiliskII/src/Unix/BasiliskII`,rom=process.env.ROM??"/workspace/projects/rpi-basilisk2-sdl2-nox/Quadra800.ROM",diskSource=process.env.DISK??"/workspace/fixtures/basilisk/images/HD200MB",display=process.env.DISPLAY??":99",cowLib=process.env.COW_LIB??"/workspace/scripts/lib/cow-disk.sh",dd=mkdtempSync(join(tmpdir(),"dont-care-fflags-disk-")),cl=spawnSync("bash",["-c",'set -euo pipefail\nsource "$1"\ncow_clone "$2" "$3/disk.img" dont-care-fflags',"bash",cowLib,diskSource,dd],{encoding:"utf8"});if(cl.status!==0){console.error(cl.stderr||"DONT_CARE_FFLAGS_FAIL clone");process.exit(1)}const disk=cl.stdout.trim().split("\n").at(-1)!;
type C={name:string,stale:string,next:string,cc:number,fpsr:string};const cases:C[]=[
{name:"stale_negative_to_single_positive",stale:"bf80 0000",next:"F23C 4400 3F80 0000",cc:2,fpsr:"00000000"},
{name:"stale_zero_to_single_negative",stale:"0000 0000",next:"F23C 4400 BF80 0000",cc:4,fpsr:"08000000"},
{name:"stale_positive_to_single_zero",stale:"3f80 0000",next:"F23C 4400 0000 0000",cc:1,fpsr:"04000000"},
{name:"stale_negative_to_byte_positive",stale:"bf80 0000",next:"F23C 5800 007F",cc:2,fpsr:"00000000"},
{name:"stale_positive_to_word_negative",stale:"3f80 0000",next:"F23C 5000 8000",cc:4,fpsr:"08000000"},
{name:"stale_negative_to_fp7_double_positive",stale:"bf80 0000",next:"F23C 5780 3FF0 0000 0000 0000",cc:2,fpsr:"00000000"},
];
function prefs(p:string,j:boolean){writeFileSync(p,[`rom ${rom}`,`disk ${disk}`,"ramsize 8388608","modelid 14","cpu 4","fpu true",`jit ${j}`,`jitfpu ${j}`,"jitcachesize 8192","screen win/640/480","nosound true","nocdrom true","nogui true","ignoresegv true",""].join("\n"))}function run(c:C,j:boolean){const td=mkdtempSync(join(tmpdir(),`dont-care-fflags-${j?"jit":"int"}-`));try{const p=join(td,"prefs");prefs(p,j);const prefix=`F23C 4400 ${c.stale} F200 003A`,prefixWords=prefix.split(/\s+/).length,nextWords=c.next.split(/\s+/).length,fmovePc=0x1000+prefixWords*2,branchPc=fmovePc+nextWords*2,branch=(0xf280+c.cc).toString(16),stream=`${prefix} ${c.next} ${branch} 000A 207C 1111 1111 6006 207C 2222 2222 2C7C A6CC ${c.cc.toString(16).padStart(4,"0")}`,fmoveHex=fmovePc.toString(16).padStart(8,"0"),branchHex=branchPc.toString(16).padStart(8,"0"),e:NodeJS.ProcessEnv={...process.env,SDL_VIDEODRIVER:"x11",DISPLAY:display,HOME:td,B2_TEST_HEX:stream,B2_TEST_INIT:"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 007fe000 271f",B2_TEST_DUMP:"1",B2_TEST_DUMP_FP:"1"};if(j)Object.assign(e,{B2_JIT_FORCE_TRANSLATE:"1",B2_TEST_TWO_PASS:"1",B2_TEST_SECOND_PC:"0x1000",B2_TEST_REPLAY_COUNT:"2",B2_TEST_FORCE_L2_RAM:"1",B2_JIT_STRICT_FULL:"1",B2_NATIVE_ASSERT_PC:"0x1000"});const q=spawnSync("timeout",["-k","5s","40s",bin,"--config",p],{encoding:"utf8",timeout:45000,env:e}),out=`${q.stdout??""}${q.stderr??""}`,ds=[...out.matchAll(/^REGDUMP:.*$/gm)].map(m=>m[0]),dump=ds.at(-1),a0=dump?.match(/\bA0=([0-9a-f]+)/i)?.[1].toLowerCase(),sr=dump?.match(/\bSR=([0-9a-f]+)/i)?.[1].toLowerCase(),fpsr=dump?.match(/\bFPSR=([0-9a-f]+)/i)?.[1].toLowerCase(),architectural=dump?.replace(/ FP[0-7]=[0-9a-f]+/gi,"");return{rc:q.status,out,dump,architectural,a0,sr,fpsr,native:out.includes("NATEXEC pc=00001000"),strict:out.includes("JIT_STRICT_SUMMARY ")&&!out.includes("strict full-JIT:")&&!out.includes("JIT_FALLBACK")}}finally{rmSync(td,{recursive:true,force:true})}}
let pass=0,fail=0;try{const selected=process.env.CASE?cases.filter(c=>c.name===process.env.CASE):cases;if(!selected.length)throw Error(`unknown CASE=${process.env.CASE}`);for(const c of selected){const i=run(c,false),j=run(c,true),equiv=i.architectural!==undefined&&i.architectural===j.architectural,exact=i.a0==="22222222"&&j.a0==="22222222"&&i.sr==="271f"&&j.sr==="271f"&&i.fpsr===c.fpsr&&j.fpsr===c.fpsr;if(i.rc===0&&j.rc===0&&equiv&&exact&&j.native&&j.strict)pass++;else{fail++;console.error(`DONT_CARE_FFLAGS_FAIL case=${c.name} int=${i.rc} jit=${j.rc} equiv=${+equiv} exact=${+exact} native=${+j.native} strict=${+j.strict}`);console.error(`interp=${i.dump??"missing"}`);console.error(`jit=${j.dump??"missing"}`);for(const l of j.out.split("\n").filter(x=>/Caught|strict full-JIT|JIT_FALLBACK|NATEXEC/.test(x)).slice(-14))console.error(l)}}}finally{spawnSync("bash",["-c",'source "$1"; cow_release "$2"',"bash",cowLib,disk]);rmSync(dd,{recursive:true,force:true})}console.log(`DONT_CARE_FFLAGS_NATIVE_MATRIX pass=${pass} fail=${fail} total=${pass+fail}`);process.exit(fail?1:0);
